version: '2'
services:
    redis:
        image: redis:5
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - webnet
    postgres:
        image: postgres:11
        volumes:
            - data-volume:/data/db
        # command: -p 5434
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
            # POSTGRES_HOST: ${DATABASE_HOST}
        networks:
            - webnet
networks:
    webnet:
volumes:
    data-volume:
